import pandas as pd

df = pd.read_csv('dec4.csv', header=None)

total_cards = 0
cards_generated = {}

def find_matches(current_row, cards_generated):
    added_cards = 0
    # Find how many matching numbers you have on the card.
    matching_nums = 0
    your_numbers = df.iloc[current_row, 2].split()
    winning_numbers = df.iloc[current_row, 1].split()
    for num in your_numbers:
        if num in winning_numbers:
            matching_nums += 1
    # For matching_nums rows below the current card, repeat the process.
    for i in range(matching_nums):
        added_cards += 1
        next_row = current_row + i + 1
        if next_row not in cards_generated:
            # We want to store the exact number of additional cards generated by a copy of a given card.
            # This way, if we get a copy of a card multiple times, we don't have to repeat the calculation.
            cards_generated[next_row] = find_matches(next_row, cards_generated)
            added_cards += cards_generated[next_row]
        else:
            added_cards += cards_generated[next_row]

    return added_cards

for i in range(df.shape[0]):
    # Find how many additional cards you win from each card
    added_cards = find_matches(i, cards_generated)
    # Add to total number of cards (+ 1 for current card)
    total_cards += added_cards + 1

print(total_cards)

